# Use the official Python base image
FROM python:3.11-slim

RUN addgroup --system madaurus && adduser --system --ingroup madaurus rabah

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chown -R rabah:madaurus /app

USER rabah

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]
